# Generated by Django 4.1.5 on 2025-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0003_apilogsmodel_apikey_id_apilogsmodel_business_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogsmodel',
            name='resource_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512, null=True),
        ),
    ]
